src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le nom ne peut pas être vide")]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "La description ne peut pas être vide")]
    private ?string $description = null;


    #[ORM\Column(type: 'time')]
    #[Assert\NotNull(message: 'Veuillez saisir une durée')]
    private ?\DateTimeInterface $duree = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Veuillez entrer la disponibilité')]
    private ?string $disponibilite = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Veuillez saisir un identifiant utilisateur')]
    private ?string $id_user = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: 'Veuillez saisir une date de création')]
    private ?\DateTimeInterface $date_de_creation = null;


    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\OneToOne(inversedBy: 'service', cascade: ['persist', 'remove'])]
    private ?Categorie $Categoriee = null;

    #[ORM\Column(nullable: true)]
    private ?int $etat = null;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

   

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDisponibilite(): ?string
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(string $disponibilite): static
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getIdUser(): ?string
    {
        return $this->id_user;
    }

    public function setIdUser(string $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getDateDeCreation(): ?\DateTimeInterface
    {
        return $this->date_de_creation;
    }

    public function setDateDeCreation(\DateTimeInterface $date_de_creation): static
    {
        $this->date_de_creation = $date_de_creation;

        return $this;
    }

   
    

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCategoriee(): ?Categorie
    {
        return $this->Categoriee;
    }

    public function setCategoriee(?Categorie $Categoriee): static
    {
        $this->Categoriee = $Categoriee;

        return $this;
    }

    public function getEtat(): ?int
    {
        return $this->etat;
    }

    public function setEtat(int $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

  
}

src/Form/ServiceType.php
<?php

namespace App\Form;

use App\Entity\Service;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a name',
                    ]),
                    new Length([
                        'min' => 3,
                        'minMessage' => 'The name must be at least {{ limit }} characters long',
                    ]),
                ],
            ])
            ->add('description', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a description',
                    ]),
                    new Length([
                        'min' => 10,
                        'minMessage' => 'The description must be at least {{ limit }} characters long',
                    ]),
                ],
            ])
            ->add('duree', DateTimeType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a duration',
                    ]),
                ],
            ])
            ->add('disponibilite', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter availability',
                    ]),
                    new Length([
                        'min' => 4,
                        'minMessage' => 'The availability must be at least {{ limit }} characters long',
                    ]),
                ],
            ])
            ->add('prix')
            ->add('date_de_creation', DateTimeType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a creation date',
                    ]),
                ],
            ])
            ->add('id_user', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a user ID',
                    ]),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Service::class,
        ]);
    }
}
        

src/Controller/ServiceController.php
<?php

namespace App\Controller;
use Knp\Snappy\Pdf;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Service;
use App\Form\ServiceType;
use App\Repository\ServiceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Historique;
use App\Entity\Rating;
use App\Form\RatingType;
use App\Repository\HistoriqueRepository;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Response\QrCodeResponse;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;




#[Route('/service')]
class ServiceController extends AbstractController
{
    #[Route('/', name: 'app_service_index', methods: ['GET'])]
    public function index(ServiceRepository $serviceRepository): Response
    {
        return $this->render('service/index.html.twig', [
            'services' => $serviceRepository->findAll(),
        ]);
    }

    #[Route('/tri', name: 'app_service_tri', methods: ['GET'])]
    public function tri(Request $request, ServiceRepository $serviceRepository): Response
    {
        $sortField = $request->query->get('sort', 'name'); // 'name' est le tri par défaut
        $sortDirection = $request->query->get('direction', 'ASC'); // 'ASC' est la direction par défaut
        
        // Assurez-vous que les paramètres de tri sont valides
        $validSortFields = ['name', 'description', 'dateDeCreation']; // Ajoutez tous les champs valides de l'entité Service ici
        $validDirections = ['ASC', 'DESC'];
    
        if (!in_array($sortField, $validSortFields) || !in_array($sortDirection, $validDirections)) {
            throw new \InvalidArgumentException('Invalid sort field or direction');
        }
    
        $services = $serviceRepository->findBySortedField($sortField, $sortDirection);
    

    
        return $this->render('service/index.html.twig', [
            'services' => $services,
        ]);
    }
    
    
    #[Route('/new', name: 'app_service_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $service = new Service();
        $service->setEtat(1);
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($service);
            $entityManager->flush();
            $historique = new Historique();
            $historique->setDescription("New service created: " . $service->getName());
            $historique->setCreatedAt(new \DateTime());
            $entityManager->persist($historique);
            $entityManager->flush();
            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('service/new.html.twig', [
            'service' => $service,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_service_show', methods: ['GET'])]
    public function show(Service $service, EntityManagerInterface $entityManager): Response
    {
        $ratings = $entityManager->getRepository(Rating::class)->findByService($service);
    
        return $this->render('service/show.html.twig', [
            'service' => $service,
            'ratings' => $ratings,
        ]);
    }
    

        #[Route('/{id}/edit', name: 'app_service_edit', methods: ['GET', 'POST'])]
        public function edit(Request $request, Service $service, EntityManagerInterface $entityManager): Response
        {
            $form = $this->createForm(ServiceType::class, $service);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager->flush();

                return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
            }
            $historique = new Historique();
        $historique->setDescription("Service edited: " . $service->getName());
        $historique->setCreatedAt(new \DateTime());
        $entityManager->persist($historique);

        $entityManager->flush();

            return $this->render('service/edit.html.twig', [
                'service' => $service,
                'form' => $form->createView(),
            ]);
        }
     #[Route('/{id}', name: 'app_service_delete', methods: ['POST'])]
public function delete(Request $request, Service $service, EntityManagerInterface $entityManager, HistoriqueRepository $historiqueRepository): Response
{
    if ($this->isCsrfTokenValid('delete'.$service->getId(), $request->request->get('_token'))) {
        $name = $service->getName(); // Store the name before deleting for historique logging

        $historique = new Historique();
        $historique->setDescription("Deleted service: " . $name);
        $historique->setCreatedAt(new \DateTime());

        $entityManager->persist($historique);
        $entityManager->remove($service);
        $entityManager->flush();
    }

    return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
}

#[Route('/export/excel', name: 'app_service_export_excel')]
public function exportExcel(ServiceRepository $serviceRepository): Response
{
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    // Define the Excel file's headers
    $headers = ['ID', 'Name', 'Description', 'Date of Creation', 'State'];

    // Set headers to the sheet
    $column = 'A';
    foreach ($headers as $header) {
        $sheet->setCellValue($column++ . '1', $header);
    }

    // Fetch all services from the database
    $services = $serviceRepository->findAll();
    $rowNumber = 2; // Start from the second row after the headers

    // Fill data to the sheet
    foreach ($services as $service) {
        $sheet->setCellValue('A' . $rowNumber, $service->getId());
        $sheet->setCellValue('B' . $rowNumber, $service->getName());
        $sheet->setCellValue('C' . $rowNumber, $service->getDescription());
        $sheet->setCellValue('D' . $rowNumber, $service->getDateDeCreation()->format('Y-m-d'));
        $sheet->setCellValue('E' . $rowNumber, $service->getEtat());
        $rowNumber++;
    }

    // Create the Excel file writer
    $writer = new Xlsx($spreadsheet);

    // Create the StreamedResponse to download the Excel file
    $response = new StreamedResponse(function () use ($writer) {
        $writer->save('php://output');
    });

    // Define the response headers
    $response->headers->set('Content-Type', 'application/vnd.ms-excel');
    $response->headers->set('Content-Disposition', 'attachment;filename="service_list.xlsx"');
    $response->headers->set('Cache-Control', 'max-age=0');

    return $response;
}


#[Route('/{id}/rate', name: 'service_rate', methods: ['GET', 'POST'])]
public function rateService(Request $request, Service $service, EntityManagerInterface $entityManager): Response
{
    $rating = new Rating();
    $rating->setService($service); // Set the service for the rating
    $form = $this->createForm(RatingType::class, $rating);
    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
        $rating = $form->getData();
        $entityManager->persist($rating);
        $entityManager->flush();
        return $this->redirectToRoute('app_service_show', ['id' => $service->getId()]);

    }

    return $this->render('service/rate.html.twig', [
        'service' => $service,
        'form' => $form->createView(),
        
    ]);
}
#[Route('/{id}/qr-code', name: 'service_qr_code', methods: ['GET'])]
public function generateQrCode(Service $service): Response
{
    $url = $this->generateUrl('app_service_show', ['id' => $service->getId()], UrlGeneratorInterface::ABSOLUTE_URL);

    $qrCode = new QrCode($url);
    $qrCode->setSize(300);

    // Assuming you're using a recent version of the library,
    // use the 'writeDataUri()' or 'writeString()' method according to your library's version.
    // The 'writeString()' method should be used with a writer, as follows:

    // Create a response object and set the content type to 'image/png'
    $response = new Response();
    $response->headers->set('Content-Type', 'image/png');

    // Use the appropriate writer to output the QR code as PNG
    $writer = new \Endroid\QrCode\Writer\PngWriter();
    $pngData = $writer->write($qrCode)->getString();

    $response->setContent($pngData);

    return $response;
}


}

templates/service/_delete_form.html.twig
<form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn">Delete</button>
</form>

templates/service/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/service/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Service{% endblock %}

{% block contentblock %}
    <h1>Edit Service</h1>

    {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}
    
    <div align="center">
        {{ include('service/_delete_form.html.twig') }}
    </div>
    
    <div align="right">
        <a href="{{ path('app_service_index') }}">
            <button type="button" class="btn btn-dark btn-rounded btn-fw">Back to List</button>
        </a>
    </div>
{% endblock %}

templates/service/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Services List{% endblock %}

{% block contentblock %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Services List</h1>
    
{#
   <div class="row justify-content-center mb-3">
       <div class="col-md-6">
           <form class="input-group mb-3" action="{{ path('app_service_search') }}" method="get">
               <input type="text" name="name" class="form-control" placeholder="Search by name" required>
               <button class="btn btn-outline-success" type="submit">Search</button>
           </form>
       </div>
   </div>
#}



    <div class="row justify-content-center mb-3">
        <div class="col-auto">
            <a href="{{ path('app_service_new') }}" class="btn btn-primary mb-3">Create New Service</a>
        </div>
        <div class="col-auto">

        <a href="{{ path('app_service_export_excel') }}" class="btn btn-primary">Export to Excel</a>

                   <a href="{{ path('app_historique') }}" class="btn btn-primary">Historique</a>
            <a href="{{ path('app_service_tri', {'sort': 'name', 'direction': 'ASC'}) }}" class="btn btn-info">Sort by Name (ASC)</a>
            <a href="{{ path('app_service_tri', {'sort': 'name', 'direction': 'DESC'}) }}" class="btn btn-info">Sort by Name (DESC)</a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-light">
                <tr>
                    <th>Actions</th>
                                                            <th>QR Code</th> <!-- New column for QR codes -->

                    <th>Name</th>
                    <th>Description</th>
                    <th>Duration</th>
                    <th>Availability</th>
                    <th>Price</th>
                    <th>Creation Date</th>
                    <th>User ID</th>
                    <th>Category Name</th>
                </tr>
            </thead>
            <tbody>
                {% for service in services %}
                <tr>
                    <td>
                        <a href="{{ path('app_service_show', {'id': service.id}) }}" class="btn btn-primary btn-sm">Show</a>
                        <a href="{{ path('app_service_edit', {'id': service.id}) }}" class="btn btn-warning btn-sm">Edit</a>
                        {% if service.Categoriee is null %}
                            <a href="{{ path('categorie_add', {'id': service.id}) }}" class="btn btn-sm btn-secondary mt-1">Add Category</a>

                        {% endif %}
                        
                    </td>
                      <td>
    <img src="{{ path('service_qr_code', {'id': service.id}) }}" alt="QR Code" class="qr-code-img">
</td>

                    <td>{{ service.name }}</td>
                    <td>{{ service.description }}</td>
                    <td>{{ service.duree ? service.duree|date('H:i:s') : 'N/A' }}</td>
                    <td>{{ service.disponibilite }}</td>
                    <td>{{ service.prix }} DT</td>
                    <td>{{ service.dateDeCreation ? service.dateDeCreation|date('Y-m-d') : 'N/A' }}</td>
                    <td>{{ service.idUser }}</td>
                    <td>{{ service.Categoriee ? service.Categoriee.name : 'No Category' }}</td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="9" class="text-center">No records found</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/service/new.html.twig
{% extends 'baselogin.html.twig' %}

{% block title %}New Service{% endblock %}

{% block contentblock %}
    <h1>Create new Service</h1>

    {{ include('service/_form.html.twig') }}

    <a href="{{ path('app_service_index') }}">back to list</a>
{% endblock %}

templates/service/rate.html.twig
{# templates/service/rate.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Rate Service{% endblock %}

{% block stylesheets %}
<style>
    /* Basic reset */
    *, *:before, *:after {
        box-sizing: border-box;
    }

    /* Remove default form styling */
    form {
        width: 300px;
        margin: 50px auto;
    }

    .star-rating {
        display: flex;
        justify-content: center;
        direction: ltr; /* Reset to default direction */
    }

    .star-rating input[type="radio"] {
        display: none;
    }

    .star-rating label {
        cursor: pointer;
        padding: 10px;
        font-size: 2rem; /* Larger star size */
    }

    /* Stars when not selected */
    .star-rating label:before {
        content: '☆'; /* Unicode hollow star */
        color: #ccc; /* Light grey color */
        transition: color 0.2s ease-in-out; /* Smooth transition */
    }

    /* Hover and checked styles */
    .star-rating label:hover:before,
    .star-rating label:hover ~ label:before,
    .star-rating input[type="radio"]:checked ~ label:before {
        content: '★'; /* Unicode filled star */
        color: #f90; /* Orange color for selected stars */
    }

    /* Hide the label text offscreen for screen readers */
    .star-rating label .visually-hidden {
        position: absolute;
        left: -10000px;
        top: auto;
        width: 1px;
        height: 1px;
        overflow: hidden;
    }

    /* Style for the optional comment field */
    .comment-field {
        margin-top: 20px;
    }

    .comment-field textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: vertical;
    }

    /* Style for the submit button */
    button[type="submit"] {
        background-color: #28a745;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease-in-out;
    }

    button[type="submit"]:hover {
        background-color: #218838;
    }
</style>
{% endblock %}

{% block body %}
    <h1>Rate Service</h1>

    {{ form_start(form) }}
        <div class="star-rating">
            {% for i in 1..5 %}
                <input type="radio" id="star{{ i }}" name="form[score]" value="{{ i }}" {{ i == form.vars.value.score ? 'checked' : '' }}>
                <label for="star{{ i }}"><span class="visually-hidden">{{ i }} star</span></label>
            {% endfor %}
        </div>
        <div class="comment-field">
            {{ form_row(form.comment) }}
        </div>
        <button type="submit">Submit Rating</button>
    {{ form_end(form) }}
{% endblock %}

templates/service/recherche.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="search-container">
        <h1 class="search-title">Recherche de service</h1>
        <form class="search-form" method="get" action="{{ path('app_service_search') }}">
            <input class="search-input" type="text" name="name" placeholder="Entrez le nom du service à rechercher" />
            <button class="search-button" type="submit">Rechercher</button>
        </form>
        
        {% if service %}
            <div class="search-results">
                <h2>Résultats de la recherche:</h2>
                <div class="service-info">
                    <!-- display service details -->
                    <p><strong>Nom:</strong> {{ service.name }}</p>
                    <p><strong>Description:</strong> {{ service.description }}</p>
                    <p><strong>Durée:</strong> {{ service.duree ? service.duree|date('H:i:s') : '' }}</p>
                    <p><strong>Disponibilité:</strong> {{ service.disponibilite }}</p>
                    <p><strong>Prix:</strong> {{ service.prix }} DT</p>
                    <p><strong>Date de création:</strong> {{ service.dateDeCreation ? service.dateDeCreation|date('Y-m-d') : '' }}</p>
                    <!-- and so on for other details -->
                </div>
            </div>
        {% else %}
            <p>No service found.</p>
        {% endif %}
    </div>
{% endblock %}

templates/service/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Service Details{% endblock %}

{% block contentblock %}
    <h1>Service Details</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ service.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ service.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ service.description }}</td>
            </tr>
            <tr>
                <th>Durée</th>
                <td>{{ service.duree ? service.duree|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Disponibilité</th>
                <td>{{ service.disponibilite }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ service.prix }}</td>
            </tr>
            <tr>
                <th>Date de création</th>
                <td>{{ service.dateDeCreation ? service.dateDeCreation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Id User</th>
                <td>{{ service.idUser }}</td>
            </tr>
        </tbody>
    </table>


<a href="{{ path('checkout', {'service_id': service.id}) }}" class="btn btn-primary">Buy this product</a>

    <a href="{{ path('app_service_index') }}">Back to List</a>
    <a href="{{ path('app_service_edit', {'id': service.id}) }}">Edit</a>

    {{ include('service/_delete_form.html.twig') }}

    <div align="right">
        <a href="{{ path('app_service_index') }}">
            <button type="button" class="btn btn-dark btn-rounded btn-fw">Back to List</button>
        </a>
    </div>
    <h3>Ratings for this Service:</h3>
<ul>
 {% for rating in ratings %}
    <li>{{ rating.getScore }} - {{ rating.getComment }}</li> {# Replace with the actual method names #}
{% else %}
    <li>No ratings yet.</li>
{% endfor %}



    <!-- Button to trigger rating modal -->
<a href="{{ path('service_rate', {'id': service.id}) }}">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#rateModal">
        Rate this service
    </button>
</a>




    <!-- Modal for rating -->
    <div class="modal fade" id="rateModal" tabindex="-1" role="dialog" aria-labelledby="rateModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="rateModalLabel">Rate this service</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Your rating form goes here -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Submit Rating</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}