src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Please enter your email')]
    #[Assert\Email(message: 'Please enter a valid email')]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];  

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
     private ?string $password = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]  
    #[Assert\NotBlank(message: 'Please enter your name')]
    #[Assert\Length(min: 3, max: 255, minMessage: 'Your name should be at least {{ limit }} characters', maxMessage: 'Your name cannot be longer than {{ limit }} characters')]
    private ?string $name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'Please enter your last name')]
    #[Assert\Length(min: 3, max: 255, minMessage: 'Your last name should be at least {{ limit }} characters', maxMessage: 'Your last name cannot be longer than {{ limit }} characters')]
    private ?string $LastName = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $UserName = null;

    #[ORM\Column]
    private ?string $role = null;

    #[ORM\Column]
    private ?string $ImagePath = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
   
    #[Assert\Length(min: 6, max: 255, minMessage: 'Your biography should be at least {{ limit }} characters', maxMessage: 'Your biography cannot be longer than {{ limit }} characters')]
    private ?string $bio = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $experience = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $education = null;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $total_jobs = null;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $rating = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    
    #[Assert\Length(min: 3, max: 255, minMessage: 'Your domain should be at least {{ limit }} characters', maxMessage: 'Your domain cannot be longer than {{ limit }} characters')]
    private ?string $domaine = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $info = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(type: 'integer',nullable: true)]
    private ?int $nbe = null;

    #[ORM\Column]
    private ?int $isBanned = 0 ;
    #[ORM\Column]
    private ?int $isVerified = 0 ;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->UserName;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(?string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function setUserName(?string $UserName): self
    {
        $this->UserName = $UserName;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->ImagePath;
    }

    public function setImagePath(string $ImagePath): self
    {
        $this->ImagePath = $ImagePath;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getExperience(): ?string
    {
        return $this->experience;
    }

    public function setExperience(?string $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getEducation(): ?string
    {
        return $this->education;
    }

    public function setEducation(?string $education): self
    {
        $this->education = $education;

        return $this;
    }

    public function getTotalJobs(): ?int
    {
        return $this->total_jobs;
    }

    public function setTotalJobs(?int $total_jobs): self
    {
        $this->total_jobs = $total_jobs;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getDomaine(): ?string
    {
        return $this->domaine;
    }

    public function setDomaine(?string $domaine): self
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(?string $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getNbe(): ?int
    {
        return $this->nbe;
    }

    public function setNbe(?int $nbe): self
    {
        $this->nbe = $nbe;

        return $this;
    }

    public function getIsBanned(): ?int
    {
        return $this->isBanned;
    }

    public function setIsBanned(int $isBanned): self
    {
        $this->isBanned = $isBanned;

        return $this;
    }
    public function getIsVerified(): ?int
    {
        return $this->isVerified;
    }

    public function setIsVerified(int $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        
        $builder
            ->add('name')
            ->add('LastName')
            ->add('UserName')
            ->add('email')
            ->add('Password', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            
            
            ->add('ImagePath', FileType::class, [
                'label' => 'Image (JPG file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([

                        'mimeTypesMessage' => 'Please upload a valid JPG document',
                    ])
                ],

            ])
                 
           ->add('Image', HiddenType::class, [
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'id' => 'Image',
                ],
            ]);
            
           if ( $options['user_role'] == 'Freelancer' ) {
            $builder
            ->add('bio')
            ->add('experience')
            ->add('education');
           }
           if ( $options['user_role'] == 'Entreprise' ) {

            $builder
            ->add('domaine')
            ->add('info')
            ->add('location')
            ->add('nbe');
           }
            
           $builder
            ->add('agreeTerms', CheckboxType::class, [
                'mapped' => false,
                'constraints' => [
                    new IsTrue([
                        'message' => 'You should agree to our terms.',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
            'user_role' => null,
        ]);
    }
}

templates/utilisateur/EditProfile.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block contentblock %}
<div class = "container"> 
<br>
         
    <h1>Edit Your profile</h1>

    {{ include('utilisateur/_form.html.twig', {'button_label': 'Update'}) }}
    <div align = "center">
    {{ include('utilisateur/_delete_form.html.twig') }}
    </div>
    <div align = "right">
        <a href="{{ path('app_utilisateur_showProfile', {'id': app.user.id}) }}">
        <button type="button" class="btn btn-dark btn-rounded btn-fw">Back to profile</button>
        </a>
        <br>
        <br>
    </div>
    </div>



{% endblock %}

templates/utilisateur/_delete_form.html.twig
<form method="post" action="{{ path('app_utilisateur_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this user?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button type="button" class="btn btn-danger btn-rounded btn-fw">Delete</button>
</form>

templates/utilisateur/_form.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'name': 'my-form', 'id': 'my-form'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning btn-rounded btn-fw">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/utilisateur/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block contentblock %}
    <h1>Edit User</h1>

    {{ include('utilisateur/_form.html.twig', {'button_label': 'Update'}) }}
    <div align = "center">
    {{ include('utilisateur/_delete_form.html.twig') }}
    </div>
    <div align = "right">
        <a href="{{ path('app_utilisateur_index') }}">
        <button type="button" class="btn btn-dark btn-rounded btn-fw">back to list</button>
        </a>
    </div>

    
{% endblock %}

templates/utilisateur/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Users List{% endblock %}

{% block contentblock %}                 

    <h1 align = 'center'>Users List</h1>
    <div align = 'center'>
    <a href="{{ path('app_utilisateur_newAdmin') }}">
                <a href="{{ path('app_utilisateur_sta2') }}" class="btn btn-info">Statistiques avec %</a>

    <button type="button" class="btn btn-primary btn-rounded btn-icon"> Create Admin </button>
    </a>
    </div>

    

    <div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Actions</th>
                
                <th>Role</th>
                <th>Email</th>
                <th>Name</th>
                <th>LastName</th>
                <th>UserName</th>
                <th>Image</th>
                <th>Bio</th>
                <th>Experience</th>
                <th>Education</th>
                <th>Total_jobs</th>
                <th>Rating</th>
                <th>Domaine</th>
                <th>Info</th>
                <th>Location</th>
                <th>Nbe</th>
                <th>IsBanned</th>
                
            </tr>
        </thead>
        <tbody>
        {% for utilisateur in utilisateurs %}
            <tr>
                <td>
                    <a href="{{ path('app_utilisateur_show', {'id': utilisateur.id}) }}">
                    <button type="button" class="btn btn-primary btn-rounded btn-fw">show</button>
                    </a>
                    <br>
                    <br>
                    <a href="{{ path('app_utilisateur_edit', {'id': utilisateur.id}) }}">
                    <button type="button" class="btn btn-warning btn-rounded btn-fw">edit</button>
                    </a>
                </td>
                
                <td>{{ utilisateur.role }}</td>
                <td>{{ utilisateur.email }}</td>
                <td>{{ utilisateur.name }}</td>
                <td>{{ utilisateur.LastName }}</td>
                <td>{{ utilisateur.UserName }}</td>
         <td><img src="{{ asset(utilisateur.ImagePath) }}" alt="Image Utilisateur" class="img-thumbnail" style="width: 50px; height: auto;"></td>
                <td>{{ utilisateur.bio }}</td>
                <td>{{ utilisateur.experience }}</td>
                <td>{{ utilisateur.education }}</td>
                {% if utilisateur.Role == 'Freelancer' %} 
                <td>{{ utilisateur.totalJobs }} Jobs</td>
                {% else %}
                <td>{{ utilisateur.totalJobs }}</td>
                {% endif %}
                {% if utilisateur.Role == 'Freelancer' %} 
                <td>{{ utilisateur.rating }}/20</td>
                {% else %}
                <td>{{ utilisateur.rating }}</td>
                {% endif %}
                <td>{{ utilisateur.domaine }}</td>
                <td>{{ utilisateur.info }}</td>
                <td>{{ utilisateur.location }}</td>
                <td>{{ utilisateur.nbe }}</td>
                 {% if utilisateur.isBanned == 0 %} 
                <td> No</td>
                {% endif %}
                {% if utilisateur.isBanned == 1 %}
                <td> Yes</td>
                {% endif %}
                
            </tr>
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    
{% endblock %}

templates/utilisateur/new.html.twig
{% extends 'baselogin.html.twig' %}


{% block title %}Welcome to our website
{% endblock %}

{% block contentblock %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<h1>
		Fill the form and click save !
	</h1>
	{% form_theme form 'bootstrap_5_layout.html.twig' %}
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning btn-rounded btn-fw">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
    <section>
    <div class = "container">
        <button id="takePictureBtn" name="takePictureBtn">Take Picture</button>
        <video id="video" autoplay muted></video>
        <canvas id="canvas" style="display: none; width:300px;height:300px;"></canvas>
        <button id="snapBtn" name="snapBtn" style="display: none;">Snap</button>
    </div>
    </section>


<script>


   const canvas = document.querySelector('#canvas');
    canvas.width = 400;
    canvas.height = 300;
    const takePictureBtn = document.querySelector('#takePictureBtn');
    const snapBtn = document.querySelector('#snapBtn');
    const form = document.querySelector('#my-form');

// Check if getUserMedia is available
takePictureBtn.addEventListener('click', function(){
if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
  // Request access to the webcam
  takePictureBtn.style.display = 'none';
  snapBtn.style.display = 'block';
  navigator.mediaDevices.getUserMedia({ video: true })
    .then(function(stream) {
      // Attach the stream to the video element
      video.srcObject = stream;
      video.play();
      video.height = 300;
      const mediaStreamTrack = stream.getVideoTracks()[0];
    })
    .catch(function(error) {
      console.error('Could not access the webcam: ' + error.message);
    });
} else {
  console.error('getUserMedia is not supported in this browser.');
  }
});
// Add event listener for the "Take Picture" button
snapBtn.addEventListener('click', function() {
  $(document).ready(function() {
  // your code here

  video.pause();

  // Draw the current frame of the video on the canvas
  var context = canvas.getContext('2d');
  context.drawImage(video, 0, 0, 400, 300);
  var dataURL = canvas.toDataURL('image/jpeg');
  var path ; 
  

  $.ajax({
    url: '/utilisateur/save-img',
    type: 'POST',
    data: {'image': dataURL},
    dataType: 'json',
    success: function (response) {
      if (response.success) {
        console.log("success");
        console.log("filename: " + response.filename);
        path = response.filename;
        const form = document.querySelector('form[name="utilisateur"]');
        const imageInput = form.querySelector('input[name="utilisateur[Image]"]');
       imageInput.value = path;
      } else {
        console.log("error: " + response.message);
      }
    } 
  });

  // Stop all video streams.
  video.srcObject.getVideoTracks().forEach(track => track.stop());
  snapBtn.style.display = 'none';
  takePictureBtn.style.display = 'block';
});
});
    </script>
    {% endblock %}
   

templates/utilisateur/newAdmin.html.twig
{% extends 'baseBack.html.twig' %}
{% block title %}Welcome to our website{% endblock %}

{% block contentblock %}
    <h1> Fill the form and click save ! </h1>

    {{ include('utilisateur/_form.html.twig') }}
 
    <div align = "right">
        <a href="{{ path('app_utilisateur_index') }}">
        <button type="button" class="btn btn-dark btn-rounded btn-fw">back to list</button>
        </a>
    </div>
{% endblock %}

templates/utilisateur/profile.html.twig
{% extends 'baseFront.html.twig' %}


{% block contentblock %}

	<section id="cta" class="cta">
		<div class="container" data-aos="zoom-in">

			<div class="text-center">
				<img src="{{ asset('' ~ app.user.ImagePath) }}" alt="cta" class="img-fluid" height="200" width="200" style="border-radius: 10%; margin-bottom: 30px;">
				{% if app.user.Role == 'Freelancer' %}
				<h1 style="color: #fff;">{{ app.user.name|upper }}
					{{ app.user.lastname|upper }}</h1>
				{% endif %}
				{% if app.user.Role == 'Entreprise' %}
				<h1 style="color: #fff;">{{ app.user.name|upper }}</h1>
				{% endif %}
				<h2 style="color: #fff;">{{app.user.username}}</h2>
				<h3 style="color: #fff;">{{app.user.email}}</h3>
				<a id="showMore" class="cta-btn" href="#pricing">
					show more
				</a>
			</div>
		</div>

	</section>


	<!-- ======= Pricing Section ======= -->
	<section id="pricing" class="pricing" style="display:none;">
		<br>
		<br>
		<div class="section-title">
			<span>Details</span>
			<h2>Details</h2>
		</div>

		{% if app.user.Role == 'Freelancer' %}
		<div class="red-container">
			<h1 style="color: #000;">{{app.user.bio}}</h1>


			<h1 style="color: #fff;">Education</h1>
			<h2 class="username">{{app.user.education}}</h2>


			<h1 style="color: #fff;">Experience</h1>
			<h2 class="username">
				{{app.user.experience}}
			</h2>


			
			<div class="rating">
				<i class="bi bi-star-fill"></i>
				<span class="rating-number">
					{{app.user.rating}}/20
				</span>
				<i class="bi bi-stack"></i>
				<span class="job-number">{{app.user.totaljobs}} Jobs</span>
			</div>

			<div class="containertwobtns">
				<a href ="{{ path('app_utilisateur_editProfile', {'id': app.user.id}) }}">
				<button class="btnEdit">Edit</button>
				</a>
				<button id="showLess" class="btnEdit" href="#cta">
					SHOW LESS
				</button>
			</div>


		</div>
		{% endif %}

		{% if app.user.role == 'Entreprise' %}

		<div class="red-container">
		<h1 style="color: #fff;">Domaine</h1>
			<h2 class= username>{{app.user.domaine}}</h2>


			<h1 style="color: #fff;">Info</h1>
			<h2 class="username">{{app.user.info}}</h2>


			<h1 style="color: #fff;">Location</h1>
			<h2 class="username">
				{{app.user.location}}
			</h2>


			
			<div class="rating">
				<i class="bi bi-people-fill"></i>
				<span class="rating-number">
					{{app.user.nbe}} employees
				</span>
			</div>

			<div class="containertwobtns">
				<a href ="{{ path('app_utilisateur_editProfile', {'id': app.user.id}) }}">
				<button class="btnEdit">Edit</button>
				</a>
				<button id="showLess" class="btnEdit" href="#cta">
					show less
				</button>
			</div>


		</div>
		{% endif %}

	</section>


	<script>
		var showbtn = document.querySelector('#showMore');
showbtn.addEventListener('click', function () {
var redContainer = document.querySelector('.pricing');
redContainer.style.display = 'block';
});

var lessbtn = document.querySelector('#showLess');
lessbtn.addEventListener('click', function () {
var redContainer = document.querySelector('.pricing');
redContainer.style.display = 'none';
document.querySelector('#cta').scrollIntoView({ behavior: 'smooth' });
});
	</script>


	<style>
		.containertwobtns {
			display: flex;
			justify-content: space-between;
			align-items: center;
		}
		.red-container {
			background-color: #cc1616;
			padding: 10px;
			border-radius: 5px;
			width: 1000px;
			margin: 0 auto;
			display: flex;
			flex-direction: column;
			align-items: center;
		}

		.username {
			color: #000;
			font-size: 24px;
			font-weight: bold;
			margin-bottom: 10px;
		}

		.email {
			font-size: 18px;
			margin-bottom: 10px;
		}

		.bio {
			font-size: 16px;
			line-height: 1.5;
			margin-bottom: 20px;
		}

		.section-title {
			font-size: 20px;
			font-weight: bold;
			margin-bottom: 10px;
		}

		.education,
		.experience {
			margin-bottom: 20px;
		}

		.education h3,
		.experience h3 {
			font-size: 18px;
			margin-bottom: 10px;
		}

		.education p,
		.experience p {
			font-size: 16px;
			line-height: 1.5;
			margin-bottom: 5px;
		}
		.rating {
			display: flex;
			justify-content: center;
			align-items: center;
			margin-top: 20px;
		}

		.rating i {
			font-size: 24px;
			margin: 0 10px;
		}

		.rating span {
			font-size: 16px;
		}
		.btnEdit {
			background-color: black;
			color: white;
			width: 150px; /* fixed width */
			border: none;
			padding: 10px;
			border-radius: 5px;
			margin-top: 20px;
			font-size: 16px;
			cursor: pointer;
			margin-right: 10px;
		}

		.btnEdit:hover {
			background-color: white;
			color: black;
		}
	</style>

{% endblock %}

templates/utilisateur/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}User{% endblock %}

{% block contentblock %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ utilisateur.name }}</td>
            </tr>
             <tr>
                <th>Email</th>
                <td>{{ utilisateur.email }}</td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td>{{ utilisateur.LastName }}</td>
            </tr>
            <tr>
                <th>UserName</th>
                <td>{{ utilisateur.UserName }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ utilisateur.role }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td><img src="{{ asset('' ~ utilisateur.ImagePath) }}" alt="User Image"></td>
            </tr>
            {% if utilisateur.role == 'Freelancer' %} 
            <tr>
                <th>Bio</th>
                <td>{{ utilisateur.bio }}</td>
            </tr>
            <tr>
                <th>Experience</th>
                <td>{{ utilisateur.experience }}</td>
            </tr>
            <tr>
                <th>Education</th>
                <td>{{ utilisateur.education }}</td>
            </tr>
            <tr>
                <th>Total_jobs</th>
                <td>{{ utilisateur.totalJobs }} Jobs </td>
            </tr>
            <tr>
                <th>Rating</th>
                <td>{{ utilisateur.rating }}/20</td>
            </tr>
            {% endif %}
            {% if utilisateur.role == 'Entreprise' %} 
            <tr>
                <th>Domaine</th>
                <td>{{ utilisateur.domaine }}</td>
            </tr>
            <tr>
                <th>Info</th>
                <td>{{ utilisateur.info }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ utilisateur.location }}</td>
            </tr>
            <tr>
                <th>Nbe</th>
                <td>{{ utilisateur.nbe }} employees </td>
            </tr>
             {% endif %}
            <tr>
                <th>IsBanned</th>
                {% if utilisateur.isBanned == 0 %} 
                <td> No</td>
                {% endif %}
                {% if utilisateur.isBanned == 1 %}
                <td> Yes</td>
                {% endif %}
            </tr>
        </tbody>
    </table>

    <div align = "center">
    <a href="{{ path('app_utilisateur_edit', {'id': utilisateur.id}) }}">
    <button class="btn btn-warning btn-rounded btn-fw">Edit</button>
    </a>
    <br>
    <br>
    {{ include('utilisateur/_delete_form.html.twig') }}
    </div>


    <div align = "right">
    <a href="{{ path('app_utilisateur_index') }}">
    <button type="button" class="btn btn-dark btn-rounded btn-fw">back to list</button>
    </a>
    </div>
{% endblock %}

templates/utilisateur/statistiques2.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 align='center'>Statistiques des Utilisateurs</h1>
    <div style="width:50%; margin:auto;">
        <canvas id="usersChart"></canvas>
    </div>

    {# Ajoutez Chart.js à votre template #}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var ctx = document.getElementById('usersChart').getContext('2d');
        var usersChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: ['Admin', 'Freelancer', 'Entreprise'],
                datasets: [{
                    label: 'Pourcentage d\'utilisateurs',
                    data: [{{ percentages.admin }}, {{ percentages.freelancer }}, {{ percentages.entreprise }}],
                    backgroundColor: [
                        'blue', // Admin
                        'green', // Freelancer
                        'red'   // Entreprise
                    ],
                    hoverOffset: 4
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                aspectRatio: 1, // Gardez une valeur de 1 pour un cercle parfait
                tooltips: {
                    enabled: true,
                    mode: 'index',
                    intersect: false,
                    bodyFontSize: 15,
                    callbacks: {
                        label: function(tooltipItem, data) {
                            var label = data.labels[tooltipItem.index] || '';
                            var value = data.datasets[0].data[tooltipItem.index];
                            var percentage = value.toFixed(2); // Fixer le nombre de décimales si nécessaire
                            return label + ': ' + percentage + '%';
                        }
                    }
                },
                animation: {
                    animateScale: true,
                    animateRotate: true
                },
                legend: {
                    position: 'bottom',
                    labels: {
                        fontSize: 14,
                        usePointStyle: true
                    }
                },
            }
        });
    </script>
{% endblock %}

{% block stylesheets %}
<style>
    #usersChart {
        max-width: 600px; // ou la taille que vous souhaitez
        max-height: 300px; // ou la taille que vous souhaitez
        margin: auto;
    }
</style>
{% endblock %}